# Generated by Django 2.2.19 on 2021-03-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
